config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get '/home', to:'main#home'
  get '/about', to:'main#about'
  get '/events', to:'main#events'
  post '/events', to:'main#create_event'
  get '/admin', to:'main#admin'

  get '/login', to:'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :image, ImageUploader
  default_scope -> { order(date: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def show
    @events = Event.all
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def home
  end

  def about
    logger.debug(session[:user_id])
  end

  def events
    @new = Event.where('date > ?', 1.day.ago)
    @previous = Event.where('date <= ?', 1.day.ago)
  end

  def create_event
    @event = Event.new(event_params)

    if event_params[:image] != nil
      img = MiniMagick::Image.read(event_params[:image])
      img.resize "150x225"
      img.write "public/uploads/hoge.jpg"
    end

    logger.debug('クリエイト！！！')
    if @event.save

    else

    end

    render 'main/home'
  end

  def admin
    @event = Event.new
  end

  private
    def event_params
      params.require(:event).permit(:name, :date, :image, :available)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      user = User.find_by(email: params[:session][:email])
      logger.debug('あああああ')
      if user && user.authenticate(params[:session][:password])
        log_in user
        logger.debug(session[:user_id])
        render "main/home"
      end

  end

  def destroy
    log_out
    render "main/home"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email,:admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # def admin?
  #   @current_user.email == "shoku.koryu@gmail.com"
  # end

  def log_out
    logger.debug('ログアウトしました')
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>食の交流会</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <link rel="stylesheet" href="https://cdn.rawgit.com/balzss/luxbar/ae5835e2/build/luxbar.min.css">

  </head>
  <body>
    <header id="luxbar" class="luxbar-fixed">
        <input type="checkbox" class="luxbar-checkbox" id="luxbar-checkbox"/>
        <div class="luxbar-menu luxbar-menu-right luxbar-menu-material-amber">
            <ul class="luxbar-navigation">
                <li class="luxbar-header">
                    <label class="luxbar-hamburger luxbar-hamburger-doublespin"
                    id="luxbar-hamburger" for="luxbar-checkbox"> <span></span> </label>
                </li>
                <li class="luxbar-item"><%= link_to "Home",   'home' %></li>
                <li class="luxbar-item"><%= link_to "About us",   'about' %></li>
                <li class="luxbar-item"><%= link_to "Events", 'events' %></li>
                <% if logged_in? %>
                  <li class="luxbar-item"><%= link_to "Admin", 'admin' %></li>
                  <li class="luxbar-item"><%= link_to "Log out", logout_path, :method => :delete %></li>
                <% end %>
            </ul>
        </div>
    </header>


    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/about.html.erb
<div class="sentences">

  <p>
    <h1>About</h1>
  <b>①理念</b><br>
  「食の化学反応をおこせる場所を作る」
  </p>

  <p>
  <b>②目的</b><br>
  食に関わる・関わりたい全て人が、「ここに来れば具体的な自分の目標、やりたいことができる。」そんな場所を作ることが目的です。
  </p>

  <p>
  <b>③理由</b><br><p>
  　実は、もともと食にあまり関心はありませんでした。
  食に関心が湧いたのはきっかけは、小2の時に発症した白血病。
  二年間という長い入院生活が、人生の大きな転機となりました。
  </p>

  <p>
  　私は本当に病院食が嫌いで...一時期は10キロ近く体重が減少し、薬の影響で髪も全て抜けました。
  自分の身体が弱っていく感覚。それは子供ながらに鮮明に記憶に残っています。
  だからこそ、年２回の外泊で家族と食べるご飯は、どんなレストランの食事よりも美味しく感じたのを今でも覚えています。
  その経験から、自分の人生の中心は「食」になり、食への求心力は人一倍強くなりました。食への関心と一口に言っても色々ある中で、私は「食の課題解決」に特に強い関心がありました。飲食店でのアルバイトを大学四年間行い、簡単に大量の食事を捨てる現場を見続けていたことが大きな動機です。自然と「フードロス」という言葉に敏感に反応するようになっていました。
  </p>
  <p>
  　ある時、海外の「Too Good To Go」というサービス記事を見つけた時、「自分がやりたいサービスはこれだ！」と思いました。Too Good To Goが起こしたフードロス革命を日本でも実現するため、仲間と共に立ち上げたのが「TABETE」です。

  実は、このTABETEを立ち上げた仲間とどこで出会ったかというと、全てこの「食の交流会」という場所なんです。私が主催したこの「とにかく食に感度が高い」人の集まりは、極めて食に対するエネルギー量が高いです。その分、自分のやりたい事を一緒にできる人と出会う確率は上がります。実際に私がそれを体験したことから、確信に変わりました。
  エンジニアが何人か集まってプロダクトを作るように、食界隈の人が集まって化学反応をおこすことも十分にありえる。その中でも、食に特化した面白いコミュニティで、ここに来れば自分の目標となる人・または仲間に出会えるような会があれば...。
  そんな場所を作るため、学生の時から地道に一人で始めて、現在に至ります。
  </p>
  </p>

  <p>
  <b>④これからのこと</b><br>
  ・FoodTech特化型のビジコン開催！
  ・食関係の企業とのコラボ企画！
  ・食分野に特化したクラファンのコミュニティを作る！
  などなど

  参加してくれた人同士で色々な企画が化学反応的に生まれるような場所にしていきます
  </p>

  <p>
  <b>⑤まとめ</b><br>
  Tech系が盛り上がっている一方、Food系はまだまだ面白い人が各所に分散していると思います。そんな人達が一同に会せれば、相当すごいこともできると思いませんか？気になった方は是非一度遊びに来てくださいね。
  </p>
  </div>

app/views/main/admin.html.erb
<div class="row">
  <% current_user %>
  <% if @current_user.admin? %>

    <h1>Create Event</h1>
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@event) do |f| %>
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>

        <%= f.label :date %><br>
        <%= f.date_field :date %><br>

        <%= f.label :image %><br>
        <%= f.file_field :image, :accept => "image/jpeg"%><br>


        <%= f.submit "Create Event", class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/main/events.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">
  <%= stylesheet_link_tag   'my_styles/events', media: 'all',
                               'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="sentences">
      <h1>Events</h1>
      <h2>New</h2>
      <div class="scroll_box">
          <% @new.each do |event| %>
          <div class="new_item">
            <%= image_tag event.image, :size => '250x175' %><br>
            <%= event.name %><br>
            <%= event.date.strftime('%Y/%m/%d') %>
          </div>
        <% end %>
      </div>


      <h2>Previous</h2>
        <div class="scroll_box">
          <% @previous.first(10).each do |event| %>
            <div class="item">
              <%= image_tag event.image, :size => '225x150' %><br>
              <%= event.name %><br>
              <%= event.date.strftime('%Y/%m/%d') %>
            </div>
          <% end %>
        </div>
      </div>

</body>

app/views/main/home.html.erb
<html>
  <head>
  <%= stylesheet_link_tag   'my_styles/home', media: 'all',
                               'data-turbolinks-track': 'reload' %>
  </head>
    <body>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>